spring.application.name=permits
spring.config.import=optional:file:.env[.properties]
server.port=${SPRING_BOOT_PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
spring.jackson.deserialization.fail-on-null-for-primitives=false
